# =============================================================================
# docker-compose.yml — BASE FILE (ไฟล์หลัก)
# =============================================================================

networks:
  odoo-net:
    external: true
  backend-net:
    external: true

volumes:
  odoo-db-data:
    external: true
  odoo-db-log:
    external: true
  odoo-filestore:
    external: true
  odoo-log:
    external: true
  nginx-log:
    external: true
