[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = ${ODOO_ADMIN_PASSWORD}
db_host = odoo-db
db_port = 5432
db_user = ${ODOO_DB_USER}
db_password = ${ODOO_DB_PASSWORD}
db_name = ${ODOO_DB_NAME}
logfile = /var/log/odoo/odoo.log
log_level = info
workers = 2
max_cron_threads = 1
